apiVersion: v1
appVersion: v0.0.4
name: prometheus-darksky-exporter
description: A Helm chart to export Dark Sky results
version: 0.1.2
home: https://github.com/billykwooten/darksky-exporter
sources:
  - https://github.com/billykwooten/darksky-exporter
maintainers:
- name: max-rocket-internet
  email: no-reply@deliveryhero.com
