gp3:
  default: true
  volumeBindingMode: WaitForFirstConsumer
gp2:
  default: false
  volumeBindingMode: WaitForFirstConsumer
io1_10:
  default: false
  volumeBindingMode: WaitForFirstConsumer
io1_20:
  default: false
  volumeBindingMode: WaitForFirstConsumer
