## How many kube-downscaler pods should run in deployment
replicaCount: 1

debug:
  enable: false

events:
  enable: true

## Namespace where kube-downscaler is going to be deployed.
# namespace:
  ## Deployment will query all namespaces if left empty:
#  active_in:
#  inactive_in:
## How frequently kube-downscaler should query applications uptime, unit is in seconds.

## Default is 60 seconds
interval: 60

rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if rbac.create is true
  serviceAccountName: default
  extraRules: []
   # - apiGroups:
   #     - argoproj.io
   #   resources:
   #     - rollouts
   #   verbs:
   #     - get
   #     - watch
   #     - list
   #     - update
   #     - patch

image:
  repository: hjacobs/kube-downscaler
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent
  args: []
    # - --include-resources=deployments,cronjobs

resources:
  limits:
    cpu: 50m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 200Mi

securityContext: {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

extraLabels: {}

# Set environment variables to override the default configuration
# By default the uptime is "always"
# More information here: https://codeberg.org/hjacobs/kube-downscaler#configuration
deployment:
  environment: {}
    # DEFAULT_UPTIME: "Mon-Fri 07:00-20:00 Europe/Berlin"

# This will periodically remove all annotations preventing downscaling
# Sometimes people forget to remove the annotations and this can incur costs
resetAnnotationsCronjob:
  enabled: false
  image: bitnami/kubectl:latest
  # Cron schedule for when to reset the annotations
  schedule: 0 7 * * *
  # A kubectl selector to identify what deployments to remove the annotation from
  labelSelectors:
    - environment=staging
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""
