apiVersion: v1
appVersion: "1.0"
description: AWS Health API Exporter for Prometheus
name: prometheus-aws-health-exporter
version: 0.1.2
home: https://github.com/Jimdo/aws-health-exporter
sources:
  - https://github.com/Jimdo/aws-health-exporter
maintainers:
- name: max-rocket-internet
  email: no-reply@deliveryhero.com
