apiVersion: v1
appVersion: v0.2.0
description: Exporter for kubernetes events
name: prometheus-k8s-events-exporter
version: 0.1.0
home: https://github.com/caicloud/event_exporter
maintainers:
- name: max-rocket-internet
  email: no-reply@deliveryhero.com
