apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-local-dns.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9253
      targetPort: 9253
  selector:
    {{- include "node-local-dns.selectorLabels" . | nindent 4 }}
