{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "node-problem-detector.fullname" . }}
  labels:
    {{- include "node-problem-detector.labels" . | nindent 4 }}
    app: {{ include "node-problem-detector.name" . }}
  annotations:
  {{- if .Values.metrics.annotations }}
    {{- toYaml .Values.metrics.annotations | nindent 4 }}
  {{- else }}
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/port: "{{ .Values.settings.prometheus_port }}"
    prometheus.io/path: /metrics
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: exporter
    port: {{ .Values.settings.prometheus_port }}
    protocol: TCP
  selector:
    app: {{ include "node-problem-detector.name" . }}
{{- end }}
