apiVersion: v1
appVersion: "0.5.0"
description: Exports sentry project metrics for prometheus.
name: prometheus-sentry-exporter
version: 0.1.1
home: https://github.com/ujamii/prometheus-sentry-exporter
sources:
  - https://github.com/ujamii/prometheus-sentry-exporter
maintainers:
- name: max-rocket-internet
  email: no-reply@deliveryhero.com
