apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "toxiproxy.fullname" . }}-proxies
  labels:
{{- include "toxiproxy.labels" . | indent 4 }}
data:
{{ (.Files.Glob (printf "consumers/%s/proxies/*" .Values.consumer.name)).AsConfig | indent 2 }}
{{ (.Files.Glob "config/status.json").AsConfig | indent 2 }}
