apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "toxiproxy.fullname" . }}-config
  labels:
{{- include "toxiproxy.labels" . | indent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
