apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-downscaler.fullname" . }}
  labels:
{{ include "kube-downscaler.labels" . | indent 4 }}
    {{- if .Values.extraLabels }}
      {{- toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-downscaler.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-downscaler.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.extraLabels }}
          {{- toYaml .Values.extraLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "kube-downscaler.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ template "kube-downscaler.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- with .Values.deployment.environment }}
        env:
        {{- range $key, $value := . }}
          {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{- end }}
        args:
        - --interval={{ .Values.interval }}
        {{- if .Values.namespace }}
        {{- if .Values.namespace.active_in }}
        - --namespace={{ .Values.namespace.active_in }}
        {{- end }}
        {{- if .Values.namespace.inactive_in }}
        - --exclude-namespaces={{ .Values.namespace.inactive_in | join "," }}
        {{- end }}
        {{- end }}
        {{- if .Values.debug.enable }}
        - --debug
        {{- end }}
        {{- if .Values.events.enable }}
        - --enable-events
        {{- end }}
        {{- with .Values.image.args }}
{{ toYaml . | indent 8 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
